# Generated by Django 2.1 on 2018-08-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ROOM',
        ),
    ]
