# Generated by Django 2.0.8 on 2018-08-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stream', '0002_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(default='abc', max_length=40)),
                ('DisplayMessage', models.CharField(default='abc', max_length=1000)),
            ],
        ),
    ]
