# Generated by Django 2.0.8 on 2018-08-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0004_auto_20180813_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='DisplayMessage',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserId',
            field=models.CharField(max_length=40),
        ),
    ]
